Bicycle Calculation Program New York to Florida

In [22]:
# Import libraries
import numpy as np
import pandas as pd
from pandas import DataFrame

In [23]:
# Initalize
Day = np.array([1, 2, 3, 4, 5])
Miles = np.array([55, 65, 50, 42, 45])
Total = np.array([0]*5)
Day, Miles, Total

(array([1, 2, 3, 4, 5]), array([55, 65, 50, 42, 45]), array([0, 0, 0, 0, 0]))

In [24]:
# Computations
Total = Miles + Total
Total = Total.cumsum()
Total

array([ 55, 120, 170, 212, 257], dtype=int32)

In [25]:
# Data 
Final_Product = np.array(list(zip(Day,Miles,Total)))
Final_Product

array([[  1,  55,  55],
       [  2,  65, 120],
       [  3,  50, 170],
       [  4,  42, 212],
       [  5,  45, 257]])

In [26]:
# Visualize Data
df = pd.DataFrame(data = Final_Product, columns=['Days', 'Miles', 'Total Miles'])
df

Days  Miles  Total Miles
0     1     55           55
1     2     65          120
2     3     50          170
3     4     42          212
4     5     45          257